title: Riccardo Coppola
url: "https://riccardocoppola.me"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://onefiniteloop.io"
footer_text: "Finite Loop LTD"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  # - name: "Resume"
  #   link: "resume.pdf"
  - name: "Blog"
    link: "https://onefiniteloop.io"
