title: Riccardo Coppola
url: "https://riccardocoppola.me"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ricca509"
footer_text: "Page design by Ankit Sultana"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Resume"
    link: "resume.pdf"
  - name: "Contact"
    link: "contact"
