title: Riccardo Coppola
url: "https://riccardocoppola.me"
baseurl: "/"

markdown: kramdown

tracking_id: "UA-156846806-1"

footer: yes
footer_nav:
  - text: "Finite Loop LTD"
    link: "https://www.onefiniteloop.io/finite-loop-ltd/"
  - text: "Blog"
    link: "https://onefiniteloop.io"
  - text: "Email me at hello@ricca509.me"
    link: "mailto:hello@ricca509.me"
  - text: "GitHub"
    link: "https://github.com/ricca509"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  # - name: "Resume"
  #   link: "resume.pdf"
  - name: "Blog"
    link: "https://onefiniteloop.io"
