name: Build

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'dev'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build         
        run: npm ci && npm run build
      