name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
      - run: npm install
      - run: npm run integration
        env:
          CI: true

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
